import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./view/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-950 fixed w-full top-0 ">
          <Navbar />
          <div
            style={{ margin: "0 12.5%" }}
            className="border-b-2 w-9/12	"
          ></div>
        </div>
        {children}
      </body>
    </html>
  );
}
